# fly.toml app configuration file generated for dani-blog-backend on 2023-09-11T18:08:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dani-blog-backend"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3011
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
